### ISSUE TITLE
iPad support

### ISSUE THREAD

**Issue by kueda** [inaturalist/iNaturalistReactNative#2118]
We disabled iPad support before soft launch to get it out there, but now we want to bring it back.

# needs design
- [ ] #2164
- [ ] #2165
- [ ] https://github.com/inaturalist/iNaturalistReactNative/issues/2166
- [ ] #2167
- [ ] #2168

# dev ready

- [x] #1838
- [ ] If #1838 is still happening and it's going to take a while to fix, enable iPad in a branch and investigate ways to get builds with iPad support into TestFlight without incorporating it into prod builds. Otherwise, just enable iPad
- [x] #2169
- [x] #2170
- [x] #2171
- [ ] #2172
- [x] #2173
- [x] #2174
- [ ] ~Log in / sign up content all needs to be 500px width max~ Probably handled by #1887
- [ ] ~Log in / sign up vertically center all content for large screens~ Probably handled by #1887
- [ ] #2175
- [x] #2176
- [x] #2177
- [ ] #2178
- [ ] #2179
- [x] #2180
- [x] #2181
- [x] #2182
- [ ] ~Explore observers & identifiers has weird space at the top of the first user in a page, only on iPad, might be related to "possible stabled collision" error~ Can't repro
- [x] #2183
