### ISSUE TITLE
Geomodel inclusion

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#2281]
# Prerequisite

- [X] [https://github.com/inaturalist/iNaturalistMLWork/issues/132](https://github.com/inaturalist/iNaturalistMLWork/issues/132)
- [X] [https://github.com/inaturalist/vision-camera-plugin-inatvision/issues/33](https://github.com/inaturalist/vision-camera-plugin-inatvision/issues/33)

# Related

- [X] [https://github.com/inaturalist/iNaturalistMLWork/issues/43](https://github.com/inaturalist/iNaturalistMLWork/issues/43)

# needs design

- [X] [MOB-424](https://linear.app/inaturalist/issue/MOB-424/design-changes-for-geomodel-integration)

# TODO: dev ready

- [X] Get altitude from location provider
- [X] AICamera: Always use location when permission is given, pass lat, long, and altitude to the vision-camera-frame-processor plugin
