### ISSUE TITLE
ObsListItem component

### ISSUE THREAD

**Issue by albullington** [inaturalist/iNaturalistReactNative#432]
<img width="388" alt="Screen Shot 2023-02-03 at 9 26 57 AM" src="https://user-images.githubusercontent.com/35536439/216668008-b97d04ae-4a59-449f-8ed0-d2d7b2a8d10a.png">

<img width="374" alt="Screen Shot 2023-02-03 at 10 04 57 AM" src="https://user-images.githubusercontent.com/35536439/216675374-297b50d4-dccb-4fbf-8d4b-dc963037d986.png">

This component is made up of a few smaller components. It should include:

Props:
- [x] `observation`: the observation being rendered
- [ ] ~~`onPress`: function that gets fired when the user taps on the item~~ We ended up moving press interaction out of this.

On the start side:
- [x] Observation photo with default size of 62 x 62 and a border radius of 8px (this *might* be a shared component with ObsGridItem... but probably simpler for it not to be)

In the middle:
- [x] Observation taxon name (#435)
- [x] Observation location (#438)
- [ ] Observation date/time (#437)

The end side should either show:
- [x] Observation status if doesn't need sync (#434)
- [ ] Upload status if needs sync (#400)

...and
- [x] gutters between the start, middle, and end sections should be 10px

FWIW, this component may need to accept props related to uploading the observation as well, but IMO we should decide how to do that when we integrate My Observations.

Full spec is [here](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?node-id=1406%3A11706&t=pd821m1YFvMVyB2E-0)

**Comment by Chrischuck** [comment]
Looks like there's a lot of overlap w/ #436, I can work on this after that PR goes in. Should be pretty simple after

**Comment by kueda** [comment]
@Chrischuck I think the current approach of just the gradient is fine for now. Looks like we're just waiting on some of the icon issues resolve at #400 for this.

**Comment by albullington** [comment]
This should be completed via #400 and #510
