### ISSUE TITLE
ActivityCount component

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#494]
Some more specs for this component:

- [x] Default color darkGray, boolean prop for white version
- [x] Add comments icon filled to font
- [x] Add comments icon not filled to font, after #518 
- [x] Add IDs icon filled to font, after #518 
- [x] Add IDs icon not filled to font, after #518 
- [x] (Potentially add components for comments and IDs with logic to show filled or not, and a11y props)
- [x] Unit test
- [x] Snapshot test

**Comment by albullington** [comment]
Closed by #495
