### ISSUE TITLE
Media Viewer umbrella issue

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#892]
The MediaViewer is accessed for different kinds of media from different screens and has different states. This issue is to make sure that overall regardless of entry point the MediaViewer behaves in the following way.

Possible media are [photos](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=510-6355&mode=dev) or [sounds](https://www.figma.com/file/MChpvx4ZrKEVVwsWKt4lkI/iNaturalist-Mobile-UI-Design?type=design&node-id=512-6701&mode=dev) with two different UIs.

The possible entry points are:
- Obs Create = Obs Edit pressing on any of the media thumbnails in the EVIDENCE section
- Obs Detail pressing on any of the media in the top photo section
- Taxon Detail pressing on any of the media in the top photo section

Prerequisites are #862 and #875 .

- [x] MediaViewer is always a modal on top of the previous screen.
- [x] It never shows the app tab bar.
- [x] Coming from Obs Create the MediaViewer shows the editing buttons for cropping and deleting the highlighted media. It does not show the copyright button.
- [x] Coming from Obs Detail the MediaViewer does never show editing buttons, irrespective of coming from current user's or other user's observations. It does show the copyright button.
- [x] Coming from Taxon Detail it never shows editing buttons. It does show the copyright button.
- [x] The copyright button has two different styles: it should say CC for all CC licenses, and then © for copyrighted images

**Comment by kueda** [comment]
With the caveat that [cropping functionality doesn't exist yet](https://github.com/inaturalist/iNaturalistReactNative/issues/970), this should be done when #966 gets merged.
