### ISSUE TITLE
Notifications umbrella issue (partly post-mvp)

### ISSUE THREAD

**Issue by jtklein** [inaturalist/iNaturalistReactNative#902]
With the re-implementation of the notifications screen we need to ensure that:

There are two types of notifications.
1. Observations-related: Four different types: Identification, comment, mention, fave [post-mvp]
3. User-related: One type for now: Follow [if this is currently not possible from API/server side we move this type to post-mvp]

Notifications on observation-related items are retrieved for:
1. Observations of the current user
2. Observations the current user follows currently

Knowledge wether unread notifications are present is acessed in several places in the app:
1. Top-level TabBar: are there unread notifications.
5. Notifications screen: are there unread notifications about comments added, id's added, mentions, faves [post-mvp], or follows.
6. ObsDetail screen: are there unread notifications about comments added, id's added, mentions, or faves [post-mvp].

Triggering a change on the API for this data will happen in those places:
1. ObsDetail: Entering the ObsDetail screen for an observation that has unread notifications associated with it triggers the marking of all of those notifications as "read" simultaneously.
3. UserProfile: Entering the UserProfile of a user that the current user has an unread "follow" notification triggers the marking of this single notification as read.
4. Notifications screen: Pressing on the green dot on the right-hand side of one notification item triggers triggers the marking of this single notification as read. [post-mvp]

In addition to the above, on a high level the re-implementation requires:
- [ ] Retrieve (and store ?) the data necessary for all notifications to be presented to the user in an appropriate level in the component tree.
- [x] Notifications screen is according to designs: #899
- [x] Tab bar icon shows red dot if there are unread notifications: #900
